[[docs]]
  name = "Overview"
  weight = 1
  url = "/cc/about/"

[[docs]]
  name = "Updates"
  weight = 5
  url = "/cc/post/"

[[docs]]
  name = "Contact"
  weight = 10
  url = "/cc/contact/"

[[global]]
  name = "About"
  weight = 1
  url = "/cc/about/"

[[global]]
  name = "Updates"
  weight = 5
  url = "/cc/post/"

[[global]]
  name = "Transparency"
  weight = 8
  url = "/transparency/"

[[global]]
  name = "Join Us"
  weight = 10
  url = "/join/"
